default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: coursehub_development
  username: postgres
  password: <%= ENV.fetch("PGPASSWORD", "1234") %>
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: coursehub_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
