default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || "password" %>
  host: <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV["PGPORT"] || 5432 %>

development:
  <<: *default
  database: coursehub_development

test:
  <<: *default
  database: coursehub_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
